import { QuizQuestion } from "../types";

export const oldTestamentQuestions: QuizQuestion[] = [
  // BEGINNER QUESTIONS (40)
  {
    id: "ot-1",
    testament: "old",
    difficulty: "beginner",
    question: "Who was the first man created by God?",
    options: ["Noah", "Adam", "Abraham", "Moses"],
    answerIndex: 1,
    reference: "Genesis 2:7",
    explanation: "Adam was formed from the dust and given life by God.",
  },
  {
    id: "ot-2",
    testament: "old",
    difficulty: "beginner",
    question: "Which prophet was swallowed by a great fish?",
    options: ["Elijah", "Jonah", "Isaiah", "Jeremiah"],
    answerIndex: 1,
    reference: "Jonah 1:17",
    explanation: "Jonah spent three days and nights in the fish.",
  },
  {
    id: "ot-3",
    testament: "old",
    difficulty: "beginner",
    question: "Who built the ark?",
    options: ["Moses", "Noah", "Abraham", "David"],
    answerIndex: 1,
    reference: "Genesis 6:14",
    explanation: "Noah built the ark according to God's instructions.",
  },
  {
    id: "ot-4",
    testament: "old",
    difficulty: "beginner",
    question: "How many days did God take to create the world?",
    options: ["5", "6", "7", "8"],
    answerIndex: 1,
    reference: "Genesis 1:31-2:2",
    explanation: "God created the world in six days and rested on the seventh.",
  },
  {
    id: "ot-5",
    testament: "old",
    difficulty: "beginner",
    question: "Who was thrown into a lion's den?",
    options: ["David", "Daniel", "Joseph", "Elijah"],
    answerIndex: 1,
    reference: "Daniel 6:16",
    explanation: "Daniel was protected by God in the lion's den.",
  },
  {
    id: "ot-6",
    testament: "old",
    difficulty: "beginner",
    question: "Which king had a dream about a statue?",
    options: ["David", "Solomon", "Nebuchadnezzar", "Herod"],
    answerIndex: 2,
    reference: "Daniel 2:1",
    explanation: "Nebuchadnezzar dreamed of a statue made of different metals.",
  },
  {
    id: "ot-7",
    testament: "old",
    difficulty: "beginner",
    question: "Who was known for his great wisdom?",
    options: ["David", "Solomon", "Moses", "Isaiah"],
    answerIndex: 1,
    reference: "1 Kings 3:12",
    explanation: "God gave Solomon wisdom greater than anyone before or after.",
  },
  {
    id: "ot-8",
    testament: "old",
    difficulty: "beginner",
    question: "Who led the Israelites out of Egypt?",
    options: ["Aaron", "Moses", "Joshua", "Joseph"],
    answerIndex: 1,
    reference: "Exodus 3:10",
    explanation: "Moses confronted Pharaoh and led the Exodus.",
  },
  {
    id: "ot-9",
    testament: "old",
    difficulty: "beginner",
    question: "Who was David's famous enemy?",
    options: ["Goliath", "Saul", "Absalom", "All of the above"],
    answerIndex: 3,
    reference: "Various",
    explanation: "David faced Goliath, King Saul's persecution, and his son Absalom.",
  },
  {
    id: "ot-10",
    testament: "old",
    difficulty: "beginner",
    question: "What were the first humans' names?",
    options: ["Adam and Eve", "Abraham and Sarah", "Noah and Naamah", "Isaac and Rebekah"],
    answerIndex: 0,
    reference: "Genesis 3:20",
    explanation: "Adam named his wife Eve because she would become the mother of all living.",
  },
  {
    id: "ot-11",
    testament: "old",
    difficulty: "beginner",
    question: "Which woman hid spies in Jericho?",
    options: ["Ruth", "Rahab", "Deborah", "Esther"],
    answerIndex: 1,
    reference: "Joshua 2:1",
    explanation: "Rahab hid the Israelite spies and was spared when Jericho fell.",
  },
  {
    id: "ot-12",
    testament: "old",
    difficulty: "beginner",
    question: "Who had a coat of many colors?",
    options: ["David", "Joseph", "Solomon", "Jonathan"],
    answerIndex: 1,
    reference: "Genesis 37:3",
    explanation: "Jacob gave Joseph a special coat, making his brothers jealous.",
  },
  {
    id: "ot-13",
    testament: "old",
    difficulty: "beginner",
    question: "What was the first plague in Egypt?",
    options: ["Frogs", "Water to blood", "Darkness", "Locusts"],
    answerIndex: 1,
    reference: "Exodus 7:20",
    explanation: "Aaron struck the Nile, turning all the water into blood.",
  },
  {
    id: "ot-14",
    testament: "old",
    difficulty: "beginner",
    question: "Who was the strongest man in the Bible?",
    options: ["Goliath", "Samson", "David", "Saul"],
    answerIndex: 1,
    reference: "Judges 16:17",
    explanation: "Samson's strength was in his hair as a Nazirite vow to God.",
  },
  {
    id: "ot-15",
    testament: "old",
    difficulty: "beginner",
    question: "What did God provide in the wilderness?",
    options: ["Manna", "Quail", "Water from a rock", "All of the above"],
    answerIndex: 3,
    reference: "Exodus 16-17",
    explanation: "God provided manna, quail, and water for the Israelites.",
  },
  {
    id: "ot-16",
    testament: "old",
    difficulty: "beginner",
    question: "Who was swallowed by a great fish?",
    options: ["Elijah", "Jonah", "Elisha", "Isaiah"],
    answerIndex: 1,
    reference: "Jonah 1:17",
    explanation: "Jonah tried to run from God and was swallowed by a fish.",
  },
  {
    id: "ot-17",
    testament: "old",
    difficulty: "beginner",
    question: "Which book begins with 'In the beginning'?",
    options: ["Exodus", "Genesis", "Psalms", "Isaiah"],
    answerIndex: 1,
    reference: "Genesis 1:1",
    explanation: "Genesis is the first book of the Bible.",
  },
  {
    id: "ot-18",
    testament: "old",
    difficulty: "beginner",
    question: "Who interpreted Pharaoh's dreams?",
    options: ["Moses", "Joseph", "Daniel", "Samuel"],
    answerIndex: 1,
    reference: "Genesis 41:25",
    explanation: "Joseph interpreted dreams of seven fat and seven thin cows.",
  },
  {
    id: "ot-19",
    testament: "old",
    difficulty: "beginner",
    question: "What were the tablets of stone called?",
    options: ["Commandments", "Testimony", "Covenant", "All of the above"],
    answerIndex: 3,
    reference: "Exodus 34:28",
    explanation: "They contained the Ten Commandments and represented God's covenant.",
  },
  {
    id: "ot-20",
    testament: "old",
    difficulty: "beginner",
    question: "Who was Isaac's father?",
    options: ["Abraham", "Jacob", "Noah", "Terah"],
    answerIndex: 0,
    reference: "Genesis 21:3",
    explanation: "Abraham was 100 years old when Isaac was born.",
  },
  {
    id: "ot-21",
    testament: "old",
    difficulty: "beginner",
    question: "What was the sign of God's covenant with Noah?",
    options: ["Circumcision", "Rainbow", "Sabbath", "Ark"],
    answerIndex: 1,
    reference: "Genesis 9:13",
    explanation: "The rainbow was a sign God would never again flood the earth.",
  },
  {
    id: "ot-22",
    testament: "old",
    difficulty: "beginner",
    question: "Who was the first king of Israel?",
    options: ["David", "Solomon", "Saul", "Jeroboam"],
    answerIndex: 2,
    reference: "1 Samuel 10:1",
    explanation: "Samuel anointed Saul as Israel's first king.",
  },
  {
    id: "ot-23",
    testament: "old",
    difficulty: "beginner",
    question: "What city did Joshua march around?",
    options: ["Jerusalem", "Jericho", "Babylon", "Nineveh"],
    answerIndex: 1,
    reference: "Joshua 6:20",
    explanation: "After seven days of marching, Jericho's walls fell down.",
  },
  {
    id: "ot-24",
    testament: "old",
    difficulty: "beginner",
    question: "Who was Moses' brother?",
    options: ["Aaron", "Miriam", "Joshua", "Both Aaron and Miriam"],
    answerIndex: 3,
    reference: "Exodus 4:14",
    explanation: "Aaron was Moses' spokesman, and Miriam was his sister.",
  },
  {
    id: "ot-25",
    testament: "old",
    difficulty: "beginner",
    question: "What did David use to defeat Goliath?",
    options: ["Sword", "Spear", "Sling and stone", "Bow and arrow"],
    answerIndex: 2,
    reference: "1 Samuel 17:49",
    explanation: "David struck Goliath in the forehead with a stone.",
  },
  {
    id: "ot-26",
    testament: "old",
    difficulty: "beginner",
    question: "Who was sold into slavery by his brothers?",
    options: ["Benjamin", "Joseph", "Judah", "Reuben"],
    answerIndex: 1,
    reference: "Genesis 37:28",
    explanation: "Joseph's brothers sold him for twenty shekels of silver.",
  },
  {
    id: "ot-27",
    testament: "old",
    difficulty: "beginner",
    question: "What was the forbidden fruit?",
    options: ["Apple", "Fig", "Grape", "Not specified"],
    answerIndex: 3,
    reference: "Genesis 3:6",
    explanation: "The Bible only says 'fruit,' not specifically apple.",
  },
  {
    id: "ot-28",
    testament: "old",
    difficulty: "beginner",
    question: "Who was the mother of Samuel?",
    options: ["Hannah", "Elizabeth", "Sarah", "Rebecca"],
    answerIndex: 0,
    reference: "1 Samuel 1:20",
    explanation: "Hannah prayed for a son and dedicated Samuel to God.",
  },
  {
    id: "ot-29",
    testament: "old",
    difficulty: "beginner",
    question: "What sea did Moses part?",
    options: ["Red Sea", "Dead Sea", "Sea of Galilee", "Mediterranean Sea"],
    answerIndex: 0,
    reference: "Exodus 14:21",
    explanation: "Moses stretched out his hand and the Red Sea divided.",
  },
  {
    id: "ot-30",
    testament: "old",
    difficulty: "beginner",
    question: "Who built the first temple in Jerusalem?",
    options: ["David", "Solomon", "Hezekiah", "Josiah"],
    answerIndex: 1,
    reference: "1 Kings 6:1",
    explanation: "Solomon built the temple his father David had planned.",
  },
  {
    id: "ot-31",
    testament: "old",
    difficulty: "beginner",
    question: "What was Jacob's name changed to?",
    options: ["Judah", "Joseph", "Israel", "Benjamin"],
    answerIndex: 2,
    reference: "Genesis 32:28",
    explanation: "Jacob wrestled with God and was renamed Israel.",
  },
  {
    id: "ot-32",
    testament: "old",
    difficulty: "beginner",
    question: "Who was the oldest person in the Bible?",
    options: ["Adam", "Noah", "Methuselah", "Abraham"],
    answerIndex: 2,
    reference: "Genesis 5:27",
    explanation: "Methuselah lived 969 years.",
  },
  {
    id: "ot-33",
    testament: "old",
    difficulty: "beginner",
    question: "What was the first murder in the Bible?",
    options: ["Cain killed Abel", "Joseph's brothers sold him", "David killed Uriah", "Saul tried to kill David"],
    answerIndex: 0,
    reference: "Genesis 4:8",
    explanation: "Cain killed his brother Abel out of jealousy.",
  },
  {
    id: "ot-34",
    testament: "old",
    difficulty: "beginner",
    question: "Who was Ruth's mother-in-law?",
    options: ["Naomi", "Orpah", "Esther", "Hannah"],
    answerIndex: 0,
    reference: "Ruth 1:4",
    explanation: "Ruth famously said to Naomi, 'Your people will be my people.'",
  },
  {
    id: "ot-35",
    testament: "old",
    difficulty: "beginner",
    question: "What did God create on the fourth day?",
    options: ["Land and sea", "Sun, moon, and stars", "Animals", "Man"],
    answerIndex: 1,
    reference: "Genesis 1:14-19",
    explanation: "God created lights to separate day from night.",
  },
  {
    id: "ot-36",
    testament: "old",
    difficulty: "beginner",
    question: "Who was the prophet who confronted David about Bathsheba?",
    options: ["Samuel", "Nathan", "Gad", "Ahijah"],
    answerIndex: 1,
    reference: "2 Samuel 12:1",
    explanation: "Nathan told David the parable of the poor man's lamb.",
  },
  {
    id: "ot-37",
    testament: "old",
    difficulty: "beginner",
    question: "What did God ask Abraham to sacrifice?",
    options: ["A lamb", "His firstborn son", "His wealth", "His home"],
    answerIndex: 1,
    reference: "Genesis 22:2",
    explanation: "God tested Abraham by asking him to sacrifice Isaac.",
  },
  {
    id: "ot-38",
    testament: "old",
    difficulty: "beginner",
    question: "Who was the first judge of Israel?",
    options: ["Deborah", "Gideon", "Samson", "Othniel"],
    answerIndex: 3,
    reference: "Judges 3:9",
    explanation: "Othniel was the first judge after Joshua's death.",
  },
  {
    id: "ot-39",
    testament: "old",
    difficulty: "beginner",
    question: "What language was most of the Old Testament written in?",
    options: ["Greek", "Hebrew", "Aramaic", "Latin"],
    answerIndex: 1,
    reference: "Original Languages",
    explanation: "Most of the Old Testament was written in Hebrew.",
  },
  {
    id: "ot-40",
    testament: "old",
    difficulty: "beginner",
    question: "Who was Shadrach, Meshach, and Abednego's friend?",
    options: ["Daniel", "Jeremiah", "Ezekiel", "Isaiah"],
    answerIndex: 0,
    reference: "Daniel 1:7",
    explanation: "All four were young Israelites taken to Babylon.",
  },

  // INTERMEDIATE QUESTIONS (40)
  {
    id: "ot-41",
    testament: "old",
    difficulty: "intermediate",
    question: "Which book contains the creation account?",
    options: ["Genesis", "Exodus", "Job", "Psalms"],
    answerIndex: 0,
    reference: "Genesis 1-2",
    explanation: "Genesis means 'beginning' and contains the creation story.",
  },
  {
    id: "ot-42",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the prophet taken to heaven in a chariot of fire?",
    options: ["Elijah", "Elisha", "Isaiah", "Jeremiah"],
    answerIndex: 0,
    reference: "2 Kings 2:11",
    explanation: "Elijah was taken to heaven without dying.",
  },
  {
    id: "ot-43",
    testament: "old",
    difficulty: "intermediate",
    question: "What were the Urim and Thummim?",
    options: [
      "Musical instruments",
      "Priestly garments",
      "Divination tools",
      "Sacred objects for discerning God's will"
    ],
    answerIndex: 3,
    reference: "Exodus 28:30",
    explanation: "Used by the high priest to determine God's will.",
  },
  {
    id: "ot-44",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the queen who saved her people?",
    options: ["Ruth", "Esther", "Deborah", "Jael"],
    answerIndex: 1,
    reference: "Esther 4:14",
    explanation: "Esther risked her life to save the Jewish people.",
  },
  {
    id: "ot-45",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'scapegoat' on the Day of Atonement?",
    options: [
      "A goat sacrificed for sins",
      "A goat sent into the wilderness",
      "Both A and B",
      "Neither A nor B"
    ],
    answerIndex: 2,
    reference: "Leviticus 16:8-10",
    explanation: "One goat was sacrificed, the other bore sins into wilderness.",
  },
  {
    id: "ot-46",
    testament: "old",
    difficulty: "intermediate",
    question: "Which prophet married a prostitute?",
    options: ["Isaiah", "Jeremiah", "Hosea", "Amos"],
    answerIndex: 2,
    reference: "Hosea 1:2",
    explanation: "God used Hosea's marriage as an object lesson for Israel's unfaithfulness.",
  },
  {
    id: "ot-47",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Jubilee' year?",
    options: [
      "Every 7th year",
      "Every 49th year",
      "Every 50th year",
      "Every 100th year"
    ],
    answerIndex: 2,
    reference: "Leviticus 25:10",
    explanation: "Every 50th year, land returned to original owners and slaves freed.",
  },
  {
    id: "ot-48",
    testament: "old",
    difficulty: "intermediate",
    question: "Who interpreted Nebuchadnezzar's dream of a tree?",
    options: ["Joseph", "Daniel", "Ezra", "Nehemiah"],
    answerIndex: 1,
    reference: "Daniel 4:19-27",
    explanation: "Daniel interpreted the dream of a great tree being cut down.",
  },
  {
    id: "ot-49",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'suffering servant' prophecy?",
    options: [
      "Isaiah 53",
      "Psalm 22",
      "Both A and B",
      "Neither A nor B"
    ],
    answerIndex: 2,
    reference: "Isaiah 53, Psalm 22",
    explanation: "Both passages describe a suffering servant, often seen as messianic.",
  },
  {
    id: "ot-50",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the high priest during David's reign?",
    options: ["Aaron", "Eli", "Abiathar", "Zadok"],
    answerIndex: 2,
    reference: "1 Samuel 22:20",
    explanation: "Abiathar served as high priest under David.",
  },
  {
    id: "ot-51",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Nazirite vow'?",
    options: [
      "A vow of poverty",
      "A vow of separation to God",
      "A vow of silence",
      "A vow of pilgrimage"
    ],
    answerIndex: 1,
    reference: "Numbers 6:2",
    explanation: "Nazirites abstained from wine, avoided corpses, and didn't cut hair.",
  },
  {
    id: "ot-52",
    testament: "old",
    difficulty: "intermediate",
    question: "Which king found the Book of the Law?",
    options: ["Hezekiah", "Josiah", "Jehoshaphat", "Joash"],
    answerIndex: 1,
    reference: "2 Kings 22:8",
    explanation: "Josiah initiated reforms after finding the Book of the Law.",
  },
  {
    id: "ot-53",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'mercy seat'?",
    options: [
      "A throne for the king",
      "The cover of the ark of the covenant",
      "A seat in the temple",
      "A prophet's chair"
    ],
    answerIndex: 1,
    reference: "Exodus 25:17",
    explanation: "The golden cover of the ark where God's presence dwelt.",
  },
  {
    id: "ot-54",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the 'weeping prophet'?",
    options: ["Isaiah", "Jeremiah", "Ezekiel", "Daniel"],
    answerIndex: 1,
    reference: "Jeremiah 9:1",
    explanation: "Jeremiah lamented Judah's impending destruction.",
  },
  {
    id: "ot-55",
    testament: "old",
    difficulty: "intermediate",
    question: "What were the 'Major Prophets'?",
    options: [
      "Isaiah, Jeremiah, Ezekiel",
      "Isaiah, Jeremiah, Daniel",
      "Isaiah, Jeremiah, Ezekiel, Daniel",
      "All the writing prophets"
    ],
    answerIndex: 2,
    reference: "Biblical Canon",
    explanation: "The four longest prophetic books: Isaiah, Jeremiah, Ezekiel, Daniel.",
  },
  {
    id: "ot-56",
    testament: "old",
    difficulty: "intermediate",
    question: "Who rebuilt Jerusalem's walls?",
    options: ["Ezra", "Nehemiah", "Zerubbabel", "Joshua"],
    answerIndex: 1,
    reference: "Nehemiah 2:17",
    explanation: "Nehemiah led the rebuilding of Jerusalem's walls.",
  },
  {
    id: "ot-57",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Valley of Dry Bones' vision?",
    options: ["Isaiah's vision", "Jeremiah's vision", "Ezekiel's vision", "Daniel's vision"],
    answerIndex: 2,
    reference: "Ezekiel 37:1-14",
    explanation: "Ezekiel saw dry bones come to life, representing Israel's restoration.",
  },
  {
    id: "ot-58",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the first high priest of Israel?",
    options: ["Moses", "Aaron", "Eleazar", "Phinehas"],
    answerIndex: 1,
    reference: "Exodus 28:1",
    explanation: "Aaron and his descendants served as priests.",
  },
  {
    id: "ot-59",
    testament: "old",
    difficulty: "intermediate",
    question: "What were the 'Cities of Refuge' for?",
    options: [
      "Levitical cities",
      "Cities for aliens",
      "Protection for unintentional killers",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Numbers 35:6",
    explanation: "Six cities where accidental killers could find protection.",
  },
  {
    id: "ot-60",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the prophetess who led Israel?",
    options: ["Deborah", "Huldah", "Miriam", "All of the above"],
    answerIndex: 3,
    reference: "Exodus 15:20, Judges 4:4, 2 Kings 22:14",
    explanation: "Miriam, Deborah, and Huldah were all prophetesses.",
  },
  {
    id: "ot-61",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Shema'?",
    options: [
      "A prayer for forgiveness",
      "A declaration of God's oneness",
      "A blessing for food",
      "A temple hymn"
    ],
    answerIndex: 1,
    reference: "Deuteronomy 6:4",
    explanation: "'Hear, O Israel: The LORD our God, the LORD is one.'",
  },
  {
    id: "ot-62",
    testament: "old",
    difficulty: "intermediate",
    question: "Who interpreted the handwriting on the wall?",
    options: ["Joseph", "Daniel", "Ezra", "Isaiah"],
    answerIndex: 1,
    reference: "Daniel 5:25-28",
    explanation: "Daniel interpreted 'MENE, MENE, TEKEL, PARSIN' for Belshazzar.",
  },
  {
    id: "ot-63",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Day of the Lord'?",
    options: [
      "The Sabbath",
      "A day of judgment and salvation",
      "Passover",
      "The Day of Atonement"
    ],
    answerIndex: 1,
    reference: "Amos 5:18",
    explanation: "A future day of both judgment and restoration.",
  },
  {
    id: "ot-64",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the prophet during the Babylonian exile?",
    options: ["Isaiah", "Jeremiah", "Ezekiel", "Daniel"],
    answerIndex: 2,
    reference: "Ezekiel 1:1",
    explanation: "Ezekiel prophesied to exiles in Babylon.",
  },
  {
    id: "ot-65",
    testament: "old",
    difficulty: "intermediate",
    question: "What were the 'Minor Prophets'?",
    options: [
      "The last 12 books of the OT",
      "Less important prophets",
      "Prophets with shorter books",
      "Both A and C"
    ],
    answerIndex: 3,
    reference: "Biblical Canon",
    explanation: "Hosea through Malachi - shorter books collectively called 'The Twelve.'",
  },
  {
    id: "ot-66",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the 'father of the faithful'?",
    options: ["Adam", "Noah", "Abraham", "Moses"],
    answerIndex: 2,
    reference: "Romans 4:11",
    explanation: "Abraham is called the father of all who believe.",
  },
  {
    id: "ot-67",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Asherah pole'?",
    options: [
      "A sacred tree",
      "A pagan fertility symbol",
      "An object of worship",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Deuteronomy 16:21",
    explanation: "A Canaanite fertility symbol often worshipped by Israelites.",
  },
  {
    id: "ot-68",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the prophet who anointed David?",
    options: ["Samuel", "Nathan", "Gad", "Ahijah"],
    answerIndex: 0,
    reference: "1 Samuel 16:13",
    explanation: "Samuel anointed David while he was still a shepherd.",
  },
  {
    id: "ot-69",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'cherubim'?",
    options: [
      "Angel-like beings",
      "Guardians of God's holiness",
      "Figures on the ark",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Exodus 25:18-20",
    explanation: "Winged creatures associated with God's presence and throne.",
  },
  {
    id: "ot-70",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the Persian king who allowed Jews to return?",
    options: ["Nebuchadnezzar", "Cyrus", "Darius", "Artaxerxes"],
    answerIndex: 1,
    reference: "Ezra 1:1",
    explanation: "Cyrus issued the decree allowing Jews to return and rebuild.",
  },
  {
    id: "ot-71",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Feast of Tabernacles'?",
    options: [
      "Commemorating Exodus",
      "Harvest festival",
      "Living in temporary shelters",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Leviticus 23:33-43",
    explanation: "Also called Sukkot, commemorating wilderness wanderings.",
  },
  {
    id: "ot-72",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the prophet who challenged Baal's prophets?",
    options: ["Elijah", "Elisha", "Isaiah", "Jeremiah"],
    answerIndex: 0,
    reference: "1 Kings 18:20",
    explanation: "Elijah's contest on Mount Carmel.",
  },
  {
    id: "ot-73",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Torah'?",
    options: [
      "The first five books",
      "The Law of Moses",
      "Jewish teaching",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Jewish Tradition",
    explanation: "Torah means 'teaching' and refers to Genesis-Deuteronomy.",
  },
  {
    id: "ot-74",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the 'Messiah' expected to be?",
    options: [
      "A political leader",
      "A spiritual savior",
      "An anointed king",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Various Prophecies",
    explanation: "Different expectations existed in Jewish thought.",
  },
  {
    id: "ot-75",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Song of Songs' about?",
    options: [
      "God's love for Israel",
      "Human romantic love",
      "Wisdom literature",
      "Both A and B"
    ],
    answerIndex: 3,
    reference: "Song of Solomon",
    explanation: "Interpreted both as human love and God's love for his people.",
  },
  {
    id: "ot-76",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the 'suffering servant' in Isaiah 53?",
    options: [
      "The prophet Isaiah",
      "The nation of Israel",
      "The coming Messiah",
      "All interpretations exist"
    ],
    answerIndex: 3,
    reference: "Isaiah 53",
    explanation: "Jewish and Christian interpretations vary.",
  },
  {
    id: "ot-77",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'Holiness Code'?",
    options: [
      "Leviticus 17-26",
      "The Ten Commandments",
      "Deuteronomic laws",
      "Priestly regulations"
    ],
    answerIndex: 0,
    reference: "Leviticus 17-26",
    explanation: "Contains laws for holy living: 'Be holy because I am holy.'",
  },
  {
    id: "ot-78",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the prophet during Nineveh's repentance?",
    options: ["Jonah", "Nahum", "Both", "Neither"],
    answerIndex: 0,
    reference: "Jonah 3:5",
    explanation: "Jonah reluctantly preached to Nineveh, and they repented.",
  },
  {
    id: "ot-79",
    testament: "old",
    difficulty: "intermediate",
    question: "What was the 'year of release'?",
    options: [
      "Every 7th year",
      "Debts canceled",
      "Land rested",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Deuteronomy 15:1",
    explanation: "Sabbatical year with debt cancellation and land rest.",
  },
  {
    id: "ot-80",
    testament: "old",
    difficulty: "intermediate",
    question: "Who was the last judge before the monarchy?",
    options: ["Samson", "Samuel", "Eli", "Deborah"],
    answerIndex: 1,
    reference: "1 Samuel 7:15",
    explanation: "Samuel was judge, prophet, and anointer of kings.",
  },

  // ADVANCED QUESTIONS (20)
  {
    id: "ot-81",
    testament: "old",
    difficulty: "advanced",
    question: "What is the 'Documentary Hypothesis'?",
    options: [
      "J, E, D, P sources",
      "Multiple authorship of Torah",
      "A theory about Pentateuch composition",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Biblical Criticism",
    explanation: "Theory that Torah compiled from multiple sources.",
  },
  {
    id: "ot-82",
    testament: "old",
    difficulty: "advanced",
    question: "Which Dead Sea Scroll is most complete?",
    options: [
      "Isaiah Scroll",
      "Psalms Scroll",
      "Temple Scroll",
      "War Scroll"
    ],
    answerIndex: 0,
    reference: "Dead Sea Scrolls",
    explanation: "The Great Isaiah Scroll (1QIsa) is nearly complete.",
  },
  {
    id: "ot-83",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'Hebrew parallelism'?",
    options: [
      "Poetic structure",
      "Synonymous thoughts",
      "A feature of wisdom literature",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Hebrew Poetry",
    explanation: "Thoughts expressed in parallel lines, common in Psalms and Proverbs.",
  },
  {
    id: "ot-84",
    testament: "old",
    difficulty: "advanced",
    question: "What was the 'Deuteronomic reform'?",
    options: [
      "Josiah's reforms",
      "Centralization of worship",
      "Based on found scroll",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "2 Kings 22-23",
    explanation: "Josiah's reforms after finding the Book of the Law.",
  },
  {
    id: "ot-85",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'apocalyptic literature'?",
    options: [
      "Revealed truth",
      "Symbolic visions",
      "End-times focus",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Daniel, Ezekiel",
    explanation: "Literature revealing divine mysteries through symbols.",
  },
  {
    id: "ot-86",
    testament: "old",
    difficulty: "advanced",
    question: "Who was 'Second Isaiah'?",
    options: [
      "Isaiah 40-55",
      "Different author",
      "Exilic prophet",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Isaiah 40-55",
    explanation: "Scholars identify different authors within Isaiah.",
  },
  {
    id: "ot-87",
    testament: "old",
    difficulty: "advanced",
    question: "What was the 'Babylonian captivity' duration?",
    options: [
      "40 years",
      "70 years",
      "400 years",
      "490 years"
    ],
    answerIndex: 1,
    reference: "Jeremiah 25:11",
    explanation: "Prophesied as 70 years of Babylonian domination.",
  },
  {
    id: "ot-88",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'Wisdom literature'?",
    options: [
      "Job, Proverbs, Ecclesiastes",
      "Practical living advice",
      "Philosophical reflection",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Wisdom Books",
    explanation: "Books dealing with practical and philosophical wisdom.",
  },
  {
    id: "ot-89",
    testament: "old",
    difficulty: "advanced",
    question: "What was the 'Synagogue' origin?",
    options: [
      "During Babylonian exile",
      "Local worship centers",
      "Replaced temple temporarily",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Exilic Period",
    explanation: "Developed during exile when temple was destroyed.",
  },
  {
    id: "ot-90",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'covenant theology'?",
    options: [
      "God's relationship framework",
      "Adam, Noah, Abraham, Moses, David, New",
      "Theological structure",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Theological Studies",
    explanation: "Understanding Scripture through God's covenants.",
  },
  {
    id: "ot-91",
    testament: "old",
    difficulty: "advanced",
    question: "What was the 'Septuagint'?",
    options: [
      "Greek OT translation",
      "3rd century BC",
      "Used by early Christians",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "LXX",
    explanation: "Greek translation of Hebrew Scriptures, circa 3rd-2nd century BC.",
  },
  {
    id: "ot-92",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'hermeneutics'?",
    options: [
      "Interpretation principles",
      "Biblical study method",
      "Understanding context",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Biblical Studies",
    explanation: "The science and art of biblical interpretation.",
  },
  {
    id: "ot-93",
    testament: "old",
    difficulty: "advanced",
    question: "What was the 'Divided Kingdom' period?",
    options: [
      "After Solomon's death",
      "Israel (North) and Judah (South)",
      "922-722/586 BC",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "1 Kings 12",
    explanation: "Kingdom split after Solomon; Israel fell 722 BC, Judah 586 BC.",
  },
  {
    id: "ot-94",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'form criticism'?",
    options: [
      "Analyzing literary forms",
      "Oral tradition study",
      "Gattungen (genres)",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Biblical Criticism",
    explanation: "Studying literary forms and their life settings.",
  },
  {
    id: "ot-95",
    testament: "old",
    difficulty: "advanced",
    question: "What was the 'Priestly source'?",
    options: [
      "P in Documentary Hypothesis",
      "Focus on ritual, genealogy",
      "Exilic period",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Pentateuchal Criticism",
    explanation: "One of hypothesized sources of Torah, emphasizing priestly matters.",
  },
  {
    id: "ot-96",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'theodicy'?",
    options: [
      "Defense of God's goodness",
      "Job's central theme",
      "Problem of evil",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Theological Studies",
    explanation: "Justifying God's justice in face of evil and suffering.",
  },
  {
    id: "ot-97",
    testament: "old",
    difficulty: "advanced",
    question: "What was the 'Amarna Letters' significance?",
    options: [
      "14th century BC correspondence",
      "Mention 'Habiru'",
      "Ancient Near East context",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Archaeology",
    explanation: "Clay tablets providing context for Late Bronze Age Canaan.",
  },
  {
    id: "ot-98",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'intertestamental period'?",
    options: [
      "400 years between OT and NT",
      "Greek and Roman rule",
      "Apocrypha written",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Historical Period",
    explanation: "Period between Malachi and Matthew's events.",
  },
  {
    id: "ot-99",
    testament: "old",
    difficulty: "advanced",
    question: "What was the 'Masoretic Text'?",
    options: [
      "Standard Hebrew text",
      "Medieval Jewish scholars",
      "Vowel points added",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Textual Transmission",
    explanation: "Authoritative Hebrew text standardized by Masoretes.",
  },
  {
    id: "ot-100",
    testament: "old",
    difficulty: "advanced",
    question: "What is 'canonical criticism'?",
    options: [
      "Studying final form",
      "Canon's shape and message",
      "Theological interpretation",
      "All of the above"
    ],
    answerIndex: 3,
    reference: "Biblical Criticism",
    explanation: "Focusing on final canonical form rather than sources.",
  }
];